project_name: seven

before:
  hooks:
    - go mod tidy

builds:
  - id: seven
    main: ./cmd/seven
    binary: seven
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: seven
    builds:
      - seven
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: marc-826
    name: seven

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
